### ISSUE TITLE
Library name change?

### ISSUE THREAD

**Issue by devrimgunduz** [arcapos/luapgsql#39]
Hi,

What do you think of changing library name from pgsql.so to luapgsql.so ? pgsql.so is very generic, and installing it under library dir may cause confusion.

Thanks!

Regards, Devrim

**Comment by mbalmer** [comment]
The file pgsql.so is not installed to a system library location, but a Lua specific directory, usually /usr/lib/lua/5.3/.  It follows the Lua naming convention which mandates that it be named pgsql.so to be found when using require 'pgsql'.  So I think that a name change is not needed, and since this module has been available under this name for years, it would probably break stuff.
